/**:
  ros__parameters:
    voxel: [0.05, 0.05, 0.0]
    crop_box_min: [0.0, -3.0, 0.0, 1.0]
    crop_box_max: [5.0, 3.0, 0.0, 1.0]
    max_cluster_size: 300
    min_cluster_size: 10
    ec_tollerance: 0.35
